version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=buy_recipe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5438:5432'